version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m TaitanXFun
    restart: always
    volumes:
      - .:/app
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - OWNER_ID=${OWNER_ID}
      - LOG_GROUP_ID=${LOG_GROUP_ID}
      - START_IMAGE_URL=${START_IMAGE_URL}
